### ISSUE TITLE
[Bug] Build Error: Failed to load plugin 'vue' declared in '.eslintrc.js': Cannot find module 'eslint/lib/util/traverser'

### ISSUE THREAD

**Issue by IAmLFish** [creativetimofficial/vuetify-material-dashboard#31]
### Version
Latest
### Operating System
macOS Mojave
### Device
Mac
### Browser & Version
Chrome
### Steps to reproduce
After cloning, running "npm install" and then "npm run dev" 
### What is expected?
I want to run the app.
### What is actually happening?
I get this error after "npm run dev"

Module build failed (from ./node_modules/eslint-loader/index.js):
Error: Failed to load plugin 'vue' declared in '.eslintrc.js': Cannot find module 'eslint/lib/util/traverser'
Referenced from: /Users/user123/Dev/vuetify-material-dashboard/.eslintrc.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:603:15)
    at Function.Module._load (internal/modules/cjs/loader.js:529:25)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/user123/Dev/vuetify-material-dashboard/node_modules/eslint-plugin-vue/lib/rules/order-in-components.js:8:19)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Module.require (internal/modules/cjs/loader.js:659:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/Users/user123/Dev/vuetify-material-dashboard/node_modules/eslint-plugin-vue/lib/index.js:37:28)
    at Module._compile (internal/modules/cjs/loader.js:723:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:734:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)

 @ multi (webpack)-dev-server/client?http://192.168.178.44:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js

---
### Additional comments
I use node v11.4.0

**Comment by TheSecEng** [comment]
This is an issue with the eslint-plugin-vue package. Just update that package.

`nom install eslint-plugin-vue -u`

**Comment by IAmLFish** [comment]
@TheSecEng oh ty, that solved it! 
Now I also understand the stack trace aswell, I was probably just blind that day.

**Comment by SPganiie** [comment]
> This is an issue with the eslint-plugin-vue package. Just update that package.
> 
> `npm install eslint-plugin-vue -u`

thx helpfull

**Comment by Deepsvyas** [comment]
> This is an issue with the eslint-plugin-vue package. Just update that package.
> 
> `npm install eslint-plugin-vue -u`

After to many research and tried many blogs, this is the solution that I found is perfectly working.

Thank you

**Comment by Lixianlai-2** [comment]
> This is an issue with the eslint-plugin-vue package. Just update that package.
> 
> `npm install eslint-plugin-vue -u`

Works, thank you man
