### ISSUE TITLE
downloaded free version, can't compile

### ISSUE THREAD

**Issue by peppeg85** [creativetimofficial/vuetify-material-dashboard#51]
hello, i've downloaded the free version to try the interface and the componentos, but i can't neither compile, i think it's a node-sass problem. 

```
"C:\Users\xxxx\WebstormProjects\vuetify-material-dashboard-master\node_modules\node-sass\build\binding.sln" (destinazione predefinita) (1) ->
"C:\Users\xxx\WebstormProjects\vuetify-material-dashboard-master\node_modules\node-sass\build\binding.vcxproj.metaproj" (destinazione predefinita) (2) ->
"C:\Users\xxx\WebstormProjects\vuetify-material-dashboard-master\node_modules\node-sass\build\binding.vcxproj" (destinazione predefinita) (4) ->
(destinazione: ClCompile) ->
  c:\users\xxx\webstormprojects\vuetify-material-dashboard-master\node_modules\node-sass\src\create_string.cpp(17): error C2664: 'v8::String::Utf8Value::Utf8Value(const v8::String::Utf8Value &)': impossibile convertire l'argomento 1 da 'v8::Local<v8::Value>'
 a 'const v8::String::Utf8Value &' [C:\Users\xxx\WebstormProjects\vuetify-material-dashboard-master\node_modules\node-sass\build\binding.vcxproj]

    Avvisi: 2
    Errori: 1

Tempo trascorso 00:00:25.89
gyp ERR! build error
gyp ERR! stack Error: `C:\Program Files (x86)\Microsoft Visual Studio\2017\BuildTools\MSBuild\15.0\Bin\MSBuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (C:\Users\xxx\WebstormProjects\vuetify-material-dashboard-master\node_modules\node-gyp\lib\build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:210:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Windows_NT 10.0.18363
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\xxx\\WebstormProjects\\vuetify-material-dashboard-master\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_l
ibrary="
gyp ERR! cwd C:\Users\xxx\WebstormProjects\vuetify-material-dashboard-master\node_modules\node-sass
gyp ERR! node -v v12.13.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
Build failed with error code: 1
npm WARN @babel/helper-create-class-features-plugin@7.8.3 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/helper-create-regexp-features-plugin@7.8.3 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN @babel/plugin-transform-named-capturing-groups-regex@7.8.3 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@8.0.6 requires a peer of @babel/core@^7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint@>=5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-node@>=7.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-promise@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-config-standard@12.0.0 requires a peer of eslint-plugin-standard@>=4.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.11 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.11: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.3 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-sass@4.9.3 postinstall script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```
anyone can help me? thank you

**Comment by juanesarango** [comment]
@peppeg85 I came here to see solutions for this error too. I found PR #45 made by @dionrodrigues fix the bug

**Comment by peppeg85** [comment]
great, thank you, so it was the node sass versione updated to 4.12.0.

now there is a big problem....this project uses the old version of vuetify, now there is the v2 and they are updating it over the time...

**Comment by juanesarango** [comment]
This guy also created this Pull Request https://github.com/creativetimofficial/vuetify-material-dashboard/pull/42 to update to Vuetify V2. The authors didn't accept it because it introduces a lot of changes that differ from their design standards. But if you have to use Version 2 consider using his [fork](https://github.com/MrJmpl3/vuetify-material-dashboard/tree/modified-version)

**Comment by peppeg85** [comment]
ok, thank you
